### ISSUE TITLE
Chihaya

### ISSUE THREAD

**Issue by NoIdeaWhyImHere** [nyaadevs/chihaya#1]
Would it be possible to update this middleware to the latest Chihaya git version? As it currently seems, hooks.go and middleware.go have changed since last year and it won't work anymore.

**Comment by TheAMM** [comment]
We've ditched Chihaya a long time ago, so likely not, unless @nyaadev is interested in maintaining this fork (likely not).
Nothing should be stopping you, though (unless Chihaya dropped hooks and middlewares or something).
Good luck!
